[package]
name = "my-macro"
version = "0.1.0"
edition = "2024"


[lib]
name = "my_macro"
path = "src/lib.rs"
proc-macro = true

[dependencies]
darling = "0.21.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.104"
